project:
  type: website

website:
  title: "Geo-PEACE"
  navbar:
    left:
      - href: 'proposal/proposal.qmd'
        text: Project Overview
      - href: 'poster/poster.qmd'
        text: Poster
      - href: 'guide/guide.qmd'
        text: User Guide
      - href: 'https://williamtjw.shinyapps.io/GeoPEACE/'
        text: Shiny App
   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

