project:
  type: website

website:
  title: "is415-g1t5-project"
  navbar:
    left:
      - href: 'proposal/proposal.qmd'
        text: Proposal
      - href: 'shinyapp/shinyapp.qmd'
        text: Shiny App
    right: 
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

