---
title: "Project Proposal"
author: William Tan Juin Wei, Marcus Jaeson Yeo, Santhya Thirumarai Selvan
date: "October 1, 2024"
date-modified: "last-modified"
---

::: {style="font-size:40px"}
**ShinyGeode**
:::

------------------------------------------------------------------------

::: {style="font-size:30px"}
**Theme: Flow and Movement Data Analytics/ Geographical Accessibility and Spatial Interaction Models**
:::

------------------------------------------------------------------------

# Problem and Motivation

Traffic congestion in Cambodia has been a serious problem for years, and often has devastating effects such as fatal accidents. In 2021, a report by the National Road Safety Committee (NRSC) and the United Nations Development Programme (UNDP) found that road traffic congestion were one of the leading causes of death in Cambodia. Based on data collected in 2019, the report discovered that on average, there were 5 deaths due to traffic **daily**. *(Phim et al., 2019)*. It was further stated that traffic congestion in the nation has risen almost 25% in the years between 2009-2019, and most of these accidents fell within the capital city of Phnom Penh.

We aim to analyze the congestion patterns in Cambodia’s urban areas. By identifying traffic hotspots, bottlenecks, and the factors exacerbating congestion, we seek to help urban planners and policymakers optimize traffic flow and develop more efficient transportation networks.

More specifically, Flow and Movement Analytics of traffic congestion hotspots in the capital city of Phnom Penh could provide insights on likely causes of traffic accidents. Other geographical analysis methods such as Exploratory Spatial Data Analysis techniques can help us identify any correlated factors that result in these congestions.

Video Links (motivation):

-   

------------------------------------------------------------------------

# Project Objectives

-   Identify and detect the crime rates hotspots, clusters, and outliers

-   Access global and local spatial autocorrelation in Crime Rates in Malaysia

------------------------------------------------------------------------

# Datasets

-   [Crime Rates working data](https://data.gov.my/data-catalogue/crime_district)
-   [Shapefile (Administrative level 0-2)](https://data.humdata.org/dataset/cod-ab-mys?)

------------------------------------------------------------------------

# Approach and Methodology

-   **Data Preparation**

    1.  Sourcing data and Importing data
    2.  Data Wrangling
        -   Processing imported data to keep only needed information

        -   Restricting study area by focusing on a particular type of crime

        -   Handling missing/duplicated data

        -   Cleaning up of data

        -   Examine data to identify patterns

        -   Joining of boundary and working data

        -   Perform a write and read to rds for easier access to variable

-   **Exploratory Data Analysis (EDA)**

    1.  Visualising graphs/maps of Crime Rates in various categories
    2.  Explore interactive or animative plots to showcase time-based flow of traffic activities

-   **Global and Local Spatial Autocorrelation**

-   **Plotting our results and Interpretation**

-   **Conclusion**

------------------------------------------------------------------------

# Bibliography

1.  Phim, R., Nick Beresford, Nimnuon Ivek, Lang Sok, Bora Phat, Richard Marshall, Iván Gonzalez de Alba, Chandarany Ouch, Sun Chanthol, Men Manvy, Prum Vantha, Boran Sattya, Tho Dalin, Uy Map, & Pich Chanbandith. (2019). Road Traffic Accidents In Cambodia. In *Road Traffic Accidents in Cambodia* \[Report\]. https://www.undp.org/sites/g/files/zskgke326/files/migration/kh/UNDP_KH_ROAD-TRAFFIC-ACCIDENT-REPORT.pdf
